//获取评论初始化
export const AXIOS_COMMENTS='AXIOS_COMMENTS';
//获取评论成功
export const AXIOS_COMMENTS_SUCCESS='AXIOS_COMMENTS_SUCCESS';
//刷新获取评论初始化
export const REFRESH_COMMENTS='REFRESH_COMMENTS';
//刷新获取评论成功
export const REFRESH_COMMENTS_SUCCESS='REFRESH_COMMENTS_SUCCESS';